//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapReduceWordCounter.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reduce", ReplyAction="http://tempuri.org/IService1/ReduceResponse")]
        System.Collections.Generic.KeyValuePair<string, int> Reduce(System.Collections.Generic.Dictionary<string, int> wordDictionary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reduce", ReplyAction="http://tempuri.org/IService1/ReduceResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, int>> ReduceAsync(System.Collections.Generic.Dictionary<string, int> wordDictionary);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MapReduceWordCounter.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MapReduceWordCounter.ServiceReference2.IService1>, MapReduceWordCounter.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.KeyValuePair<string, int> Reduce(System.Collections.Generic.Dictionary<string, int> wordDictionary) {
            return base.Channel.Reduce(wordDictionary);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, int>> ReduceAsync(System.Collections.Generic.Dictionary<string, int> wordDictionary) {
            return base.Channel.ReduceAsync(wordDictionary);
        }
    }
}
